name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    name: Quality Control
    runs-on: ubuntu-latest

    steps:
      - name: checkout source code
        uses: actions/checkout@v4

      - name: install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: enable Rust caching
        uses: Swatinem/rust-cache@v2

      - name: rustfmt
        run: cargo fmt --all -- --check

      - name: clippy
        run: cargo clippy --all-targets -- -D warnings

      - name: cargo check
        run: cargo check --all-targets

      - name: cargo test
        run: cargo test
