on:
  pull_request:
  push:
    branches:
      - master

name: tests

jobs:
  tests:
    name: cargo test
    runs-on: ubuntu-latest
    steps:
      - uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo test --release
